[workspace]
resolver = "2"
members = [
    "crates/gscp-core",
    "crates/gscp-player",
    "crates/gscp-app",
]

[workspace.package]
version = "1.2.2"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
log = "0.4"
env_logger = "0.11"
regex = "1"
tempfile = "3"
libc = "0.2"

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
opt-level = "z"

# 交互密集的渲染/解码路径保留速度优先
[profile.release.package.gscp-player]
opt-level = 3
