#!/usr/bin/env bash
# 生成 gen/android/tauri.settings.gradle。
#
# 该文件由 tauri CLI 在 `tauri android build` 时生成；本项目定制了 BuildTask.kt
# 直接调用 cargo，绕过 CLI，因此需要在 gradle 之前自行生成。
# 它把 settings.gradle 里的 :tauri-android 指向 cargo registry 中
# tauri crate 自带的 mobile/android Gradle 工程。
set -euo pipefail
cd "$(dirname "$0")/.."

CARGO_HOME_DIR="${CARGO_HOME:-$HOME/.cargo}"

# 从 Cargo.lock 解析锁定的 tauri 版本
TAURI_VER=$(awk '/^name = "tauri"$/{getline; sub(/version = /, ""); gsub(/"/, ""); print; exit}' Cargo.lock)
if [ -z "$TAURI_VER" ]; then
  echo "错误：未能从 Cargo.lock 解析 tauri 版本" >&2
  exit 1
fi

# 定位 registry 源码目录（需先执行过一次 cargo build/fetch 以解包源码）
DIR=$(ls -d "$CARGO_HOME_DIR"/registry/src/*/tauri-"$TAURI_VER"/mobile/android 2>/dev/null | head -n1 || true)
if [ -z "$DIR" ]; then
  echo "错误：未找到 tauri $TAURI_VER 的 registry 源码目录。请先执行一次 cargo build（如 cargo fetch 后构建）。" >&2
  exit 1
fi

OUT="crates/gscp-app/gen/android/tauri.settings.gradle"
mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
include ':tauri-android'
project(':tauri-android').projectDir = new File("$DIR")
EOF
echo "已生成 $OUT -> $DIR"
